### PR TITLE
Optional middleware retry on connection failures

### LINKED ISSUE #147: "Call to a member function getStatusCode() on null" on ConnectException with RetryMiddlewareFactory
I'm trying to retry the request on receiving `GuzzleHttp\Exception\ConnectException` (my requests time out sometimes). For that I'm using the `MicrosoftAzure\Storage\Common\Middlewares\RetryMiddleware` like this:

	$this->tableService->pushMiddleware(RetryMiddlewareFactory::create());

I emulate the connection problems by specifying dummy endpoint when creating the storage service (`TableEndpoint=http://127.0.0.1:1002;` - a random IP address and port), `ConnectException` is raised but with RetryMiddleware I get this error:

```
Call to a member function getStatusCode() on null in
.../src/Common/Middlewares/RetryMiddlewareFactory.php:171
```

That's because the retry decider (created by `createRetryDecider()`) ignores `ConnectException` here:
https://github.com/Azure/azure-storage-php/blob/1afdf1c788a729ed486a6ef1c2e74d3db7b199b9/azure-storage-common/src/Common/Middlewares/RetryMiddlewareFactory.php#L160-L167

And assigns `null` to `$response` and then it's trying to call `getStatusCode()` on `null` here:
https://github.com/Azure/azure-storage-php/blob/1afdf1c788a729ed486a6ef1c2e74d3db7b199b9/azure-storage-common/src/Common/Middlewares/RetryMiddlewareFactory.php#L169-L173

I'd like to fix the issue, and there are several options how to do that:
1. Don't retry on `ConnectException`
2. Retry on `ConnectException`
3. Let the developer decide whether they want to when creating the middleware – the retry decider would accept one more parameter: `$retryConnect = false`.

I'd like to see number 3. and can submit a pull request for that (or any other option), please let me know.

Thank you!

### PR DESCRIPTION
**Pull request by spaze**
This modifies the retry decider to (optionally) retry also on connection failures.

Fix #147

### CODE REVIEW

**Comment by Oxicode** [comment]
+1

File: azure-storage-common/src/Common/Middlewares/RetryMiddlewareFactory.php [hunk 1]
```diff
@@ -136,11 +141,12 @@ public static function create(
      *
      * @param  string $type       The type of the retry handler.
      * @param  int    $maxRetries The maximum number of retries to be done.
+     * @param  bool   $retryConnect Whether to retry on connection failures.
```
Comment (katmsft) [inline azure-storage-common/src/Common/Middlewares/RetryMiddlewareFactory.php]: Indentation here is not aligned. Please modify L142 and L143 as well.

File: azure-storage-common/src/Common/Middlewares/RetryMiddlewareFactory.php [hunk 2]
```diff
@@ -136,11 +141,12 @@ public static function create(
...
      *
      * @return callable     The callable that will return if the request should
      *                      be retried.
      */
-    protected static function createRetryDecider($type, $maxRetries)
+    protected static function createRetryDecider($type, $maxRetries, $retryConnect = false)
```
Comment (katmsft) [inline azure-storage-common/src/Common/Middlewares/RetryMiddlewareFactory.php]: I don't think the default value is necessary here.

**Comment by katmsft** [comment]
Thanks for the contribution, I have some minor comments. Please make the changes and I'll run the full validation when the changes are made.
@XiaoningLiu any thoughts?

**Comment by spaze** [comment]
Thank you. I've now addressed both comments.

**Comment by katmsft** [comment]
Sorry I missed [this line](https://github.com/Azure/azure-storage-php/pull/148/files#diff-78cb7236670c32f5b64de01456670d5eR97), please pass 3 arguments instead of 2, since the method now takes 3 arguments with no default value.

**Comment by spaze** [comment]
@katmsft Oh yeah, sorry. Ran a different test that didn't catch it, updated. Thanks!
