### PR TITLE
Fix prefix issue

### LINKED ISSUE #27: BlobRestProxy::listBlobs issues with a prefix with a comma (,)
**Reproduce**
1. Create a blob called: `my dir, and that/subdir/blob.txt`
2. Try to list blobs inside the `my dir, and that` "directory"

**Sample Code**

``` php
$container_name = 'test-container';

$options = new ListBlobsOptions();
$options->setDelimiter('/');
$options->setPrefix('my dir, and that/')

try {
    // This will throw an exception for a 403 response
    $blob_list = $this->blob_proxy->listBlobs(
        $container_name,
        $options
    );
} catch (\Exception $e) {
    // ...
}
```

**Error Response**

```
Fail:
Code: 403
Value: Server failed to authenticate the request. Make sure the value of Authorization header is formed correctly including the signature.
details (if any): ﻿<?xml version="1.0" encoding="utf-8"?><Code>AuthenticationFailed</Code><Message>Server failed to authenticate the request. Make sure the value of Authorization header is formed correctly including the signature.
RequestId:bce16b9e-0001-0094-15dc-f4e755000000
Time:2016-08-12T20:59:37.6311976Z</Message><AuthenticationErrorDetail>The MAC signature found in the HTTP request '###' is not the same as any computed signature. Server used following string to sign: 'GET




application/x-www-form-urlencoded
Fri, 12 Aug 2016 20:59:38 GMT





x-ms-version:2015-04-05
/testaccount/test-container
comp:list
delimiter:/
prefix:my dir, and that/
restype:container'.</AuthenticationErrorDetail>.
```

**Potential Issue**
From the [documentation](https://msdn.microsoft.com/en-us/library/azure/dd179428.aspx) to build the Canonicalized Resource String for _2009-09-19 and later Shared Key Format_:

> If a query parameter has more than one value, sort all values lexicographically, then include them in a comma-separated list:
> parameter-name:parameter-value-1,parameter-value-2,parameter-value-n

I believe this is not being considered by the SDK, taking into account that the prefix does not seem to be able to have multiple values. For query parameters that cannot have more than one value, I would expect the SDK to do whatever is needed for it to be interpreted as a single value, and not many values (URL encoding the comma character prevents the error from being raised but it does not return the appropriate results).

### PR DESCRIPTION
**Pull request by dluces**
There is an issue with the generation of the authentication header when the request includes a single-value query parameter that includes the separator character in its value. For example, when listing blobs with a prefix that has a `,` (comma) in it. This PR fixes this issue.

Fixes #27

### CODE REVIEW

**Comment by dluces** [comment]
@katmsft I just ran `phpunit -c phpunit.xml.dist --filter testComputeCanonicalizedResourceMockMultipleValues` and the test is passing. The test was modified in this PR to use `ServiceRestProxy::groupQueryValues` which should be ordering the values. Can you give me more info on how you're running the test and the output please? Here's mine:

```
diego@laptop azure-storage-php (fix_prefix_issue) $ phpunit -c phpunit.xml.dist --filter testComputeCanonicalizedResourceMockMultipleValues
PHPUnit 4.8.27 by Sebastian Bergmann and contributors.

Runtime:	PHP 7.0.6
Configuration:	/Users/diego/projects/contribute/azure-storage-php/phpunit.xml.dist
Warning:	The Xdebug extension is not loaded
		No code coverage will be generated.

.

Time: 135 ms, Memory: 12.00MB

OK (1 test, 1 assertion)

```

File: tests/unit/Common/Internal/Authentication/StorageAuthSchemeTest.php [hunk 1]
```diff
@@ -94,7 +95,13 @@ public function testComputeCanonicalizedResourceMockMultipleValues()
     {
         $queryVariables = array();
         $queryVariables['COMP'] = 'list';
-        $queryVariables[Resources::QP_INCLUDE] = 'snapshots,metadata,uncommittedblobs';
+        $queryVariables[Resources::QP_INCLUDE] = ServiceRestProxy::groupQueryValues(
```
Comment (dluces) [inline tests/unit/Common/Internal/Authentication/StorageAuthSchemeTest.php]: @katmsft This should be ordering the values for the following call to `computeCanonicalizedResourceMock`.

Comment (katmsft) [inline tests/unit/Common/Internal/Authentication/StorageAuthSchemeTest.php]: Ah, I see, sorry that I missed this modification.

**Comment by dluces** [comment]
Hello @katmsft, do you have an estimate on when this would make it to a new release?

**Comment by katmsft** [comment]
We are currently working on concurrent upload and streaming the response/request body to solve some issues, it will be released once we finished that. I could not personally give you an estimate but we also wish to deliver the newest release as soon as possible. In the meantime I will try to push this pull request to be merged so at least people can use these code in dev branch.

**Comment by dluces** [comment]
@katmsft rebased off of dev and fixed conflicts
